enableEconomy: true
itemResaleValue: 5.0
currencyName: Elite Coins
useVault - not recommended: false
enableCurrencyShower: true
currencyShowerTierMultiplier: 1.0
chatCurrencyShowerMessage: '&7[EM] Du hast &a$amount $currency_name gesammelt!'
actionbarCurrencyShowerMessage: '&7[EM] Du hast &a$amount $currency_name gesammelt!'
adventurersGuildNotificationMessage: '&7[EM] Noch Geld übrig? Guck mal bei &a/ag &7oder
  &a/em shop&7!'
lootShowerMaterials:
  '1': GOLD_NUGGET
  '5': GOLD_INGOT
  '10': GOLD_BLOCK
  '20': EMERALD_BLOCK
materialWorth:
  DIAMOND_AXE: 20.0
  DIAMOND_BOOTS: 20.0
  DIAMOND_CHESTPLATE: 20.0
  DIAMOND_LEGGINGS: 20.0
  DIAMOND_HELMET: 20.0
  DIAMOND_PICKAXE: 20.0
  DIAMOND_SHOVEL: 20.0
  DIAMOND_SWORD: 20.0
  DIAMOND_HOE: 20.0
  IRON_AXE: 16.0
  IRON_BOOTS: 16.0
  IRON_LEGGINGS: 16.0
  IRON_CHESTPLATE: 16.0
  IRON_HELMET: 16.0
  IRON_PICKAXE: 16.0
  IRON_SHOVEL: 16.0
  IRON_HOE: 16.0
  IRON_SWORD: 16.0
  SHIELD: 16.0
  BOW: 16.0
  CHAINMAIL_BOOTS: 13.0
  CHAINMAIL_LEGGINGS: 13.0
  CHAINMAIL_CHESTPLATE: 13.0
  CHAINMAIL_HELMET: 13.0
  STONE_SWORD: 13.0
  STONE_AXE: 13.0
  STONE_PICKAXE: 13.0
  STONE_SHOVEL: 13.0
  STONE_HOE: 13.0
  GOLDEN_AXE: 10.0
  GOLDEN_BOOTS: 10.0
  GOLDEN_LEGGINGS: 10.0
  GOLDEN_CHESTPLATE: 10.0
  GOLDEN_HELMET: 10.0
  GOLDEN_SWORD: 10.0
  GOLDEN_SHOVEL: 10.0
  GOLDEN_PICKAXE: 10.0
  GOLDEN_HOE: 10.0
  GOLDEN_APPLE: 20.0
  ENCHANTED_GOLDEN_APPLE: 20.0
  LEATHER_BOOTS: 10.0
  LEATHER_LEGGINGS: 10.0
  LEATHER_CHESTPLATE: 10.0
  LEATHER_HELMET: 10.0
  WOODEN_SWORD: 10.0
  WOODEN_AXE: 10.0
  WOODEN_HOE: 10.0
  WOODEN_PICKAXE: 10.0
  TRIDENT: 20.0
  ELYTRA: 20.0
  TURTLE_HELMET: 10.0
  defaultMaterialWorth: 1.0
